name: Tests
on: [push, pull_request]
jobs:
  tests:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python-version: [3.9, '3.10', '3.11', '3.12', '3.13', pypy-3.10]
        # It is difficult to install libxml2 and libxslt development packages on Windows.
        # https://www.lfd.uci.edu/~gohlke/pythonlibs/ distributes a wheel, but the URL changes.
        exclude:
          - os: windows-latest
            python-version: pypy-3.10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: pyproject.toml
      - if: matrix.os == 'ubuntu-latest' && matrix.python-version == 'pypy-3.10'
        run: |
          sudo apt-get update
          sudo apt-get install libxml2-dev libxslt-dev
      - run: pip install .[test]
      - run: coverage run --source=scrapyd_client -m pytest
      - if: matrix.os == 'ubuntu-latest'
        run: bash <(curl -s https://codecov.io/bash)
      - run: pip install -U check-manifest setuptools
      - run: check-manifest
